name: Déploiement GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Installe pnpm
        run: npm install -g pnpm

      - name: Installe les dépendances
        run: pnpm install

      - name: Génère le site
        run: pnpm build

      - name: Injecte <base> dans index.html
        run: |
          sed -i 's|<head>|<head>\n  <base href="/mon-diaporama-slidev/">|' dist/index.html

      - name: Déploie sur gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
